language: generic
before_install:
  - sudo apt-get install g++ ant cmake zip byacc flex automake libtool binutils-dev libiberty-dev bison python2.7 libncurses5-dev
  - sudo updatedb
script:
  - jenkins build
  - export DORIS_HOME=`pwd`
  - wget http://180.76.53.174:8090/installed.tgz
  - tar -zxf palo-thirdparty.tgz -C thirdparty
  - ./env.sh
  - ./run-ut.sh
  - ./run-fe-ut.sh
  - #exit 0
  - #wget http://palo-opensource.gz.bcebos.com/palo-thirdparty-20180927.tar.gz?authorization=bce-auth-v1/069fc2786e464e63a5f1183824ddb522/2018-09-27T02:03:00Z/-1/host/d049d39d29749caad0d1d1cbbd66fda409415bbd97baa06e6358f88531bd6619 -O thirdparty/palo-thirdparty.tar.gz
  - #tar -zxf thirdparty/palo-thirdparty.tar.gz -C thirdparty
  - #mkdir -p thirdparty/src
  - #mv thirdparty/palo-thirdparty*/* thirdparty/src
  - #sh thirdparty/build-thirdparty.sh
  - #bash build.sh --fe --be

