# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name:  Doris CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: check fe code style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: $GITHUB_WORKSPACE/fe
      
      - name: install dependency
        run: sudo apt-get install g++ ant cmake zip byacc flex automake libtool binutils-dev libiberty-dev bison python2.7 libncurses5-dev lsb-release mlocate
      
      - name: checkout source code
        uses: actions/checkout@v2
        
      - name: Cache m2
        id: cache m2
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: 
             ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
             ${{ runner.os }}-maven-
        
      - name: build thirdparty
        run: |
              export REPOSITORY_URL=https://doris-incubating-repo.bj.bcebos.com/thirdparty
              export DORIS_HOME=$GITHUB_WORKSPACE
              cd $GITHUB_WORKSPACE/
              bash env.sh
              bash thirdparty/concurrent-build-thirdparty.sh
              
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: build fe
        run: |
          cd $GITHUB_WORKSPACE
          bash build.sh --be
        
      - name: fe ut
        run: |
          cd $GITHUB_WORKSPACE
          bash run-fe-ut.sh
      
      - name: Generate fe coverage report
        run: |
          cd $GITHUB_WORKSPACE
          bash run-fe-ut.sh --coverage
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: $GITHUB_WORKSPACE/fe/target/site/cobertura/*.html
          flags: unittests
          name: codecov
          
      - name: build be
        run: |
          cd $GITHUB_WORKSPACE
          bash build.sh --be
          
      - name: be ut
        run: |
          cd $GITHUB_WORKSPACE
          bash run-ut.sh 
