# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  # This workflow contains a single job called "build"
  build:
    name: doris build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
     
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # pull docker image && run
      - name: use docker image
        run:  docker pull apachedoris/doris-dev:build-env-1.2
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name : test
        run: echo $GITHUB_WORKSPACE

      # dock path map the code path
      - name: path map
        run:  docker run -d --name doris-env -v $GITHUB_WORKSPACE:/root/incubator-doris apachedoris/doris-dev:build-env-1.2 
      # Runs a single command using the runners shell
      
      - name: time sleep
        run:  sleep 5
      
      - name: test1
        run:  docker ps
        
      - name: Run BE build
        run:  docker exec doris-env bash -c "cd /root/incubator-doris; sh build.sh --be"

      # Runs a set of commands using the runners shell
      - name: Run FE build
        run:  docker exec doris-env bash -c "cd /root/incubator-doris; sh build.sh --fe"
       
      
 
